const { ADD_POST, UPDATE_POST, DELETE_POST, APPROVE_POST, DECLINE_POST,
     GET_ALL_PENDING_POSTS, GET_POST_BY_ID } = require("../../endPoints/endPoints");

module.exports = [
    ADD_POST, UPDATE_POST, APPROVE_POST, DECLINE_POST, DELETE_POST,
    GET_ALL_PENDING_POSTS, GET_POST_BY_ID
]